export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";

//users
export const USER_LOADING = "USER_LOADING";
export const USERS_LOADING = "USERS_LOADING";
export const USER_SAVED = "USER_SAVED";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";
export const USER_ERROR = "USER_ERROR";
export const USER_DELETED = "USER_DELETED";
export const USER_UPDATED = "USER_UPDATED";

//change page
export const CHANGE_PAGE = "CHANGE_PAGE";

//alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";


//products

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCT_SAVED = "PRODUCT_SAVED";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";

//customers

export const CUSTOMER_LOADING = "CUSTOMER_LOADING";
export const CUSTOMERS_LOADING = "CUSTOMERS_LOADING";
export const CUSTOMER_SAVED = "CUSTOMER_SAVED";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const CUSTOMERS_ERROR = "CUSTOMERS_ERROR";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CUSTOMER_DELETED = "CUSTOMER_DELETED";
export const CUSTOMER_UPDATED = "CUSTOMER_UPDATED";

//rentproduct
export const RENTPRODUCT_LOADING = "RENTPRODUCT_LOADING";
export const RENTPRODUCTS_LOADING = "RENTPRODUCTS_LOADING";
export const RENTPRODUCT_SAVED = "RENTPRODUCT_SAVED";
export const GET_RENTPRODUCT = "GET_RENTPRODUCT";
export const GET_RENTPRODUCTS = "GET_RENTPRODUCTS";
export const GET_LASTRECORD = "GET_LASTRECORD";
export const RENTPRODUCT_ERROR = "RENTPRODUCT_ERROR";
export const RENTPRODUCTS_ERROR = "RENTPRODUCTS_ERROR";
export const RENTPRODUCT_DELETED = "RENTPRODUCT_DELETED";
export const RENTPRODUCT_UPDATED = "RENTPRODUCT_UPDATED";

//returnproduct
export const RETURNPRODUCT_LOADING = "RETURNPRODUCT_LOADING";
export const RETURNPRODUCTS_LOADING = "RETURNPRODUCTS_LOADING";
export const RETURNPRODUCT_SAVED = "RETURNPRODUCT_SAVED";
export const GET_RETURNPRODUCT = "GET_RETURNPRODUCT";
export const GET_RETURNPRODUCTS = "GET_RETURNPRODUCTS";
export const RETURNPRODUCT_ERROR = "RETURNPRODUCT_ERROR";
export const RETURNPRODUCTS_ERROR = "RETURNPRODUCTS_ERROR";
export const RETURNPRODUCT_DELETED = "RETURNPRODUCT_DELETED";
export const RETURNPRODUCT_UPDATED = "RETURNPRODUCT_UPDATED";
export const GET_RETURNORDER = "GET_RETURNORDER";


//orders

export const ORDER_LOADING = "ORDER_LOADING";
export const ORDERS_LOADING = "ORDERS_LOADING";
export const ORDER_SAVED = "ORDER_SAVED";
export const GET_ORDER = "GET_ORDER";
export const GET_ORDERS = "GET_ORDERS";
export const ORDER_ERROR = "ORDER_ERROR";
export const ORDERS_ERROR = "ORDERS_ERROR";
export const ORDER_DELETED = "ORDER_DELETED";
export const ORDER_UPDATED = "ORDER_UPDATED";


//appointment

export const APPOINTMENT_LOADING = "APPOINTMENT_LOADING";
export const APPOINTMENTS_LOADING = "APPOINTMENTS_LOADING";
export const APPOINTMENT_SAVED = "APPOINTMENT_SAVED";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const APPOINTMENT_ERROR = "APPOINTMENT_ERROR";
export const APPOINTMENTS_ERROR = "APPOINTMENTS_ERROR";
export const APPOINTMENT_DELETED = "APPOINTMENT_DELETED";
export const APPOINTMENT_UPDATED = "APPOINTMENT_UPDATED";

//report
export const GET_REPORT = "GET_REPORT";
export const REPORT_ERROR = "REPORTS_ERROR";
export const REPORT_LOADING = "REPORT_LOADING";


// dashbaord
export const SHOP_STARTED = "SHOP_STARTED";
export const SHOP_STOPPED = "SHOP_STOPPED";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_LOADED = "DASHBOARD_LOADED";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const SHOP_LOADING = "SHOP_LOADING";
export const SHOP_LOADED = "SHOP_LOADED";
export const SHOP_ERROR = "SHOP_ERROR";


//Invoices

export const INVOICE_LOADING = "INVOICE_LOADING";
export const INVOICES_LOADING = "INVOICES_LOADING";
export const INVOICE_SAVED = "INVOICE_SAVED";
export const GET_INVOICE = "GET_INVOICE";
export const GET_INVOICES = "GET_INVOICES";
export const INVOICES_ERROR = "INVOICES_ERROR";
export const INVOICE_ERROR = "INVOICE_ERROR";
export const INVOICE_DELETED = "INVOICE_DELETED";
export const INVOICE_UPDATED = "INVOICE_UPDATED";

